#!/bin/sh

echo "Running ESLint on staged files..."

# Run ESLint on staged files
npx eslint ./src/mainloop.js
ESLINT_EXIT_CODE=$?

# Check if ESLint passed
if [ $ESLINT_EXIT_CODE -ne 0 ]; then
  echo "ESLint failed. Fix the issues before committing."
  exit 1
fi

echo "All files have passed."

exit 0