#!/bin/sh
# Prepend the branch name to the commit message

BRANCH_NAME=$(git symbolic-ref --short HEAD)
MSG_FILE=$1

# Prepend the branch name to the first line of the commit message
sed -i.bak "1s/^/[$BRANCH_NAME] /" "$MSG_FILE"

echo "Branch name [$BRANCH_NAME] has been added to the commit message."